site_name: blog
site_description: an example blog set up following the blog tutorials
site_url: https://github.com/mathewgeola/

theme:
  name: material
  language: zh
  features:
    - navigation.indexes

plugins:
  - search:
      lang:
        - zh
  - blog:
      blog_toc: true
      archive_date_format: "yyyy年MM月"
      categories_allowed:
        - AOSP
        - Ubuntu
        - Holidays
        - News
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 首页: index.md
  - 标签: tags.md
  - 博客:
      - 博客首页: blog/index.md
      - 博客标签: blog/tags.md