site_name: 博客
site_description: 博客
site_url: https://github.com/mathewgeola/

theme:
  name: material

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    code: Roboto Mono

  direction: ltr

  language: zh

  features:
    - navigation.indexes
    - content.code.copy # Code copy button
    - content.code.select
    - content.code.annotate

plugins:
  - search:
      lang:
        - zh
  - blog:
      blog_toc: true
      archive_date_format: "yyyy年MM月"
      categories_allowed:
        - AOSP
        - Platform
        - Holidays
        - News
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: mathewgeola
      link: mathewgeola@gmail.com

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 首页: index.md
  - 标签: tags.md
  - 博客:
      - 博客首页: blog/index.md
      - 博客标签: blog/tags.md